name: 'dbt_snowflake_airflow'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbt_snowflake_airflow:
    staging:
      +schema: staging
      +materialized: view
      snowflake_warehouse: compute_wh
    marts:
      +database: sales_customer_analytics
      +schema: dw_marts
      +materialized: table
      snowflake_warehouse: compute_wh

